/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'semrush-s\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-s-adposition-bottom': '&#xe900;',
		'icon-s-adposition-side': '&#xe901;',
		'icon-s-adposition-top': '&#xe902;',
		'icon-s-alert': '&#xe903;',
		'icon-s-aligncenter': '&#xe904;',
		'icon-s-alignleft': '&#xe905;',
		'icon-s-alignright': '&#xe906;',
		'icon-s-android': '&#xe907;',
		'icon-s-apple': '&#xe908;',
		'icon-s-banner': '&#xe909;',
		'icon-s-banner2': '&#xe90a;',
		'icon-s-bell': '&#xe90b;',
		'icon-s-blocked': '&#xe90c;',
		'icon-s-book': '&#xe90d;',
		'icon-s-brackets': '&#xe90e;',
		'icon-s-bulb': '&#xe90f;',
		'icon-s-calendar': '&#xe910;',
		'icon-s-cart': '&#xe911;',
		'icon-s-chain': '&#xe912;',
		'icon-s-chart': '&#xe913;',
		'icon-s-chat': '&#xe914;',
		'icon-s-chek': '&#xe915;',
		'icon-s-chrome': '&#xe916;',
		'icon-s-clock': '&#xe917;',
		'icon-s-close': '&#xe918;',
		'icon-s-close2': '&#xe919;',
		'icon-s-crown': '&#xe91a;',
		'icon-s-cut': '&#xe91b;',
		'icon-s-delete': '&#xe91c;',
		'icon-s-demo': '&#xe91d;',
		'icon-s-desktop': '&#xe91e;',
		'icon-s-dislike': '&#xe91f;',
		'icon-s-document': '&#xe920;',
		'icon-s-down': '&#xe921;',
		'icon-s-download': '&#xe922;',
		'icon-s-dropdown': '&#xe923;',
		'icon-s-dropleft': '&#xe924;',
		'icon-s-dropright': '&#xe925;',
		'icon-s-dropup': '&#xe926;',
		'icon-s-edit': '&#xe927;',
		'icon-s-education': '&#xe928;',
		'icon-s-enter': '&#xe929;',
		'icon-s-expand': '&#xe92a;',
		'icon-s-export': '&#xe92b;',
		'icon-s-facebook': '&#xe92c;',
		'icon-s-fire': '&#xe92d;',
		'icon-s-firefox': '&#xe92e;',
		'icon-s-foursquare': '&#xe92f;',
		'icon-s-gplus': '&#xe930;',
		'icon-s-group': '&#xe931;',
		'icon-s-health': '&#xe932;',
		'icon-s-heart': '&#xe933;',
		'icon-s-heart2': '&#xe934;',
		'icon-s-hide': '&#xe935;',
		'icon-s-home': '&#xe936;',
		'icon-s-import': '&#xe937;',
		'icon-s-infinity': '&#xe938;',
		'icon-s-info': '&#xe939;',
		'icon-s-info2': '&#xe93a;',
		'icon-s-instagram': '&#xe93b;',
		'icon-s-key': '&#xe93c;',
		'icon-s-label': '&#xe93d;',
		'icon-s-left': '&#xe93e;',
		'icon-s-like': '&#xe93f;',
		'icon-s-link': '&#xe940;',
		'icon-s-linkedin': '&#xe941;',
		'icon-s-list': '&#xe942;',
		'icon-s-mail': '&#xe943;',
		'icon-s-megaphone': '&#xe944;',
		'icon-s-microphone': '&#xe945;',
		'icon-s-minus': '&#xe946;',
		'icon-s-mobile': '&#xe947;',
		'icon-s-move': '&#xe948;',
		'icon-s-moveble': '&#xe949;',
		'icon-s-opera': '&#xe94a;',
		'icon-s-pin': '&#xe94b;',
		'icon-s-pinterest': '&#xe94c;',
		'icon-s-plus': '&#xe94d;',
		'icon-s-popup': '&#xe94e;',
		'icon-s-question': '&#xe94f;',
		'icon-s-reccuring': '&#xe950;',
		'icon-s-redirect': '&#xe951;',
		'icon-s-redo': '&#xe952;',
		'icon-s-repeat': '&#xe953;',
		'icon-s-report': '&#xe954;',
		'icon-s-resizeh': '&#xe955;',
		'icon-s-resizew': '&#xe956;',
		'icon-s-retweet': '&#xe957;',
		'icon-s-right': '&#xe958;',
		'icon-s-rss': '&#xe959;',
		'icon-s-safari': '&#xe95a;',
		'icon-s-search': '&#xe95b;',
		'icon-s-serp': '&#xe95c;',
		'icon-s-settings': '&#xe95d;',
		'icon-s-share': '&#xe95e;',
		'icon-s-show': '&#xe95f;',
		'icon-s-skype': '&#xe960;',
		'icon-s-smilehappy': '&#xe961;',
		'icon-s-smileneutral': '&#xe962;',
		'icon-s-smilesad': '&#xe963;',
		'icon-s-speaker': '&#xe964;',
		'icon-s-star': '&#xe965;',
		'icon-s-star2': '&#xe966;',
		'icon-s-table': '&#xe967;',
		'icon-s-telescope': '&#xe968;',
		'icon-s-tile': '&#xe969;',
		'icon-s-time': '&#xe96a;',
		'icon-s-twitter': '&#xe96b;',
		'icon-s-undo': '&#xe96c;',
		'icon-s-unpin': '&#xe96d;',
		'icon-s-up': '&#xe96e;',
		'icon-s-upload': '&#xe96f;',
		'icon-s-user': '&#xe970;',
		'icon-s-vk': '&#xe971;',
		'icon-s-youtube': '&#xe972;',
		'icon-s-museum': '&#xe973;',
		'icon-s-check2': '&#xe974;',
		'icon-s-coins': '&#xe975;',
		'icon-s-crosshair': '&#xe976;',
		'icon-s-down2': '&#xe977;',
		'icon-s-export-doc': '&#xe978;',
		'icon-s-form': '&#xe979;',
		'icon-s-frame': '&#xe97a;',
		'icon-s-instagram2': '&#xe97b;',
		'icon-s-left2': '&#xe97c;',
		'icon-s-lightning': '&#xe97d;',
		'icon-s-linkedin2': '&#xe97e;',
		'icon-s-magicwand': '&#xe97f;',
		'icon-s-pause': '&#xe980;',
		'icon-s-picture': '&#xe981;',
		'icon-s-return': '&#xe982;',
		'icon-s-right2': '&#xe983;',
		'icon-s-source': '&#xe984;',
		'icon-s-text': '&#xe985;',
		'icon-s-toxic': '&#xe986;',
		'icon-s-up2': '&#xe987;',
		'icon-s-vacation': '&#xe988;',
		'icon-s-amp-project': '&#xe989;',
		'icon-s-backlink-broken': '&#xe98a;',
		'icon-s-backlink-part': '&#xe98b;',
		'icon-s-backlink': '&#xe98c;',
		'icon-s-checklist': '&#xe98d;',
		'icon-s-drawer': '&#xe98e;',
		'icon-s-hotkey': '&#xe98f;',
		'icon-s-lock': '&#xe990;',
		'icon-s-pulse': '&#xe991;',
		'icon-s-question2': '&#xe992;',
		'icon-s-tablet': '&#xe993;',
		'icon-s-webpages': '&#xe994;',
		'icon-s-archive': '&#xe995;',
		'icon-s-clean': '&#xe996;',
		'icon-s-clip': '&#xe997;',
		'icon-s-export-doc2': '&#xe998;',
		'icon-s-goblet': '&#xe999;',
		'icon-s-hourglass': '&#xe99a;',
		'icon-s-magnet': '&#xe99b;',
		'icon-s-pinall': '&#xe99c;',
		'icon-s-toxic2': '&#xe99d;',
		'icon-s-ungroup': '&#xe99e;',
		'icon-s-copy': '&#xe99f;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-s-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
